name: Terraform Checks

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Checks for all days
        run: |
          for dir in terraform-lab/day*; do
            echo "Running in $dir"
            cd $dir

            terraform init
            terraform fmt -check
            terraform validate
            terraform plan

            cd - > /dev/null
          done